src/API/Unsupported/ChannelEvent.ts
src/API/Unsupported/UnsupportedAPI.ts

As is tradition this is completely untested. And yes, I don't care if that endpoint has pagination or anything, it probably has, since it has a `_total` but I've never seen a channel that had enough events queued to require this...

feat: add unsupported kraken events endpoint

---

src/API/Channel/ChannelAPI.ts
src/API/Channel/ChannelSubscription.ts

Adds a new method to ChannelAPI for retrieving the total subscription count for a channel.
Refactors the existing getSubscriptions method to utilize a private common API data retrieval method.
Fixes #23

support retrieving total number of channel subscriptions

---

packages/twitch-chat-client/src/ChatClient.ts

In the application I've been building, I'm wanting to know when I don't have permissions on a channel that I attempt to host.
This PR adds an event listener for the no_permission NOTICE that Twitch responds with when you attempt to execute a command (such as /host) on a channel that you do not have permission to execute it on.
There's not a lot of data available in the response from Twitch, just the channel that you attempted to execute a command on without permissions.

Add event handler for no_permission event

---

packages/twitch-chat-client/src/ChatClient.ts

Right now all non-anonymous giftsubs lack information about the gifter due to the wrong check for `isAnon`

Get gifter info when gift was *not* anonymous

---

packages/twitch-webhooks/src/Subscriptions/SubscriptionEventSubscription.ts
packages/twitch-webhooks/src/WebHookListener.ts
packages/twitch/src/API/Helix/Subscriptions/HelixSubscription.ts
packages/twitch/src/API/Helix/Subscriptions/HelixSubscriptionEvent.ts
packages/twitch/src/API/Helix/WebHooks/HelixWebHooksAPI.ts
packages/twitch/src/index.ts

https://dev.twitch.tv/docs/api/webhooks-reference/#topic-subscription-events
- Adds `SubscriptionEventSubscription` for twitch-webhooks
- Creates a new `HelixSubscriptionEvent` class that extends from `HelixSubscription` due to the way that the event's payload is structured.
Testing this was a bit difficult, but when sending some mock events with Postman, everything worked fine for me and the event fired properly.

Add support for subscription webhooks

---

packages/twitch-chat-client/package.json
packages/twitch-chat-client/src/ChatClient.ts

This event is fired when a message fails to send due to internal twitch rate-limiting.

Added event listener for msg_ratelimit

---

packages/twitch/src/API/Helix/HelixPaginatedRequestWithTotal.ts

It was set to deffault 1 but twitch API allow only between 10 to 100. I set it to 20 (Twitch API deffault).
Maybe should add some logic later to take a parameter to choose pagination size.

Fixed the getTotalCount methode.

---

packages/twitch/src/API/Helix/Subscriptions/HelixSubscriptionAPI.ts

The default type of Kraken makes `twitchClient.helix.subscriptions.getSubscriptions` call `/kraken/subscriptions` which 404's and isn't the intended behavior.

Fix missing Helix call type for SubscriptionsAPI

---

packages/twitch-webhooks/package.json

Related to #122 
The published `twitch-webhooks` package is missing the `es` directory:
https://github.com/d-fischer/twitch/blob/eff58e113e2e8ac8228b4711f2a181e7131d8bd4/packages/twitch-webhooks/package.json#L43-L47

[next] fix(twitch-webhooks): publish `es` directory

---

packages/twitch-chat-client/src/ChatClient.ts

Adds the ability for `ChatClient` to receive a custom `hostName`.
Fixes #132

Allow custom hostnames

---

packages/twitch-pubsub-client/src/Messages/PubSubRedemptionMessage.ts

Type: Feature
Fixes: #147 
This adds a rewardImage getter to the PubSubRedemptionMessage class so it's possible to obtain the image set associated with redeemed reward.

Add rewardImage to PubSubRedemptionMessage

---

packages/twitch-chat-client/package.json
packages/twitch-chat-client/src/ChatClient.ts
packages/twitch-pubsub-client/package.json
yarn.lock

Type: Bugfix
Fixes: #177 
Re-registers the internal `onPrivmsg` handler that emits the `onMessage` events on `removeListener`.
I hope the way I did it is fine, otherwise just let me know.

Readd internal ChatClient onPrivmsg handler on removeListener

---

packages/twitch-chat-client/src/ChatClient.ts

Type: Bugfix
Fixes: #161
Changes the client so that instead of manually disconnecting after an auth failure, it will instead try to reconnect.
If the auth was previously valid, then the most likely case is that the existing auth token which was previously used and verified has expired. In this case, it will attempt a reconnect right away.
If the auth was previously invalid, or never verified, it instead waits 5 seconds before reconnecting so that fetching auth/reconnecting is not spammed.
I have manually tested this personally, and it fixes the reconnection issue for me as described in #161

Fix reconnection issue with expired tokens

---

packages/twitch-chat-client/src/ChatClient.ts
packages/twitch-chat-client/src/Toolkit/UserTools.ts

Type: Feature
Fixes: #138
- `enableSlow()` - Checks delay is an integer between 1 and 1800.
- `enableFollowersOnly()` - Checks delay is an integer between 0 and 129600.
- `timeout()` - Checks duration is an integer between 1 and 1209600.
This does not currently complete whole issue. The issue also requires a sanity check of usernames and channel names to be resolved.

Throw errors for incorrect chat command parameters

---

packages/twitch/src/API/Helix/User/HelixUser.ts

Type: Feature
Fixes: #211
Add the missing `created_at` response field that was added with the Developer Day in November 2020.
Ref: https://twitch.uservoice.com/forums/310213-developers/suggestions/37682716-add-created-timestamp-to-helix-users

add 'created_at' to HelixUser

---

packages/twitch-eventsub/src/Events/EventSubStreamOnlineEvent.ts

Fixes: #218
Adds a "startDate" getter for the new `started_at` property of the StreamOnline EventSub event.

Add startDate to StreamOnline EventSub event

---

packages/twitch-eventsub/src/Subscriptions/EventSubSubscription.ts

Type: **Bugfix**
Fixes: discussed on Discord
> Relevant messages:
> * https://discord.com/channels/325552783787032576/350012219003764748/807358365025697852
> * https://discord.com/channels/325552783787032576/350012219003764748/807379612887547945
> * https://discord.com/channels/325552783787032576/350012219003764748/807437261817118741
While trying to implement graceful exiting for my app using the `twitch-eventsub` package, I noticed that the `Promise` returned from unsubscription calls for `EventSub` listeners never seem to get resolved or rejected.
It seems that the initial `EventSub` implementation included code copied over from the `Webhooks` functionality and assumed that Twitch sent an unsubscription confirmation message. ([Webhooks …

Fix EventSub unsubscriptions by removing code relevant for the Webhooks implementation

---

.eslintrc.js
packages/twitch-eventsub/src/Events/EventSubChannelBanEvent.ts
packages/twitch-eventsub/src/Events/EventSubChannelUnbanEvent.ts

Fixes: #226
This PR adds:
- New EventSub `channel.ban` properties
- Moderator user ID/login/display name getters, `getModerator`
- `reason`
- `endDate` - Will be `null` for timeouts.
- `isPermanent`
- New EventSub `channel.unban` properties
- Moderator user ID/login/display name getters, `getModerator`
- Additional `.eslintrc` exceptions

add EventSub ban/unban props: mod,reason,end,perm

---

packages/twitch/src/API/Helix/Stream/HelixStream.ts

Fixes: As discussed in Discord
This PR adds a `gameName` property to the `HelixStream` object as documented [here](https://dev.twitch.tv/docs/api/reference#get-streams)

Added gameName property to HelixStream

---

packages/twitch-pubsub-client/src/Messages/PubSubSubscriptionMessage.ts

Type: Feature
Fixes: https://github.com/twurple/twurple/issues/270
This PR adds contexts for multimonth sub gifts, so that the right data gets returned when these events get triggered.

Add resubgift and anonresubgift contexts to the pubsub subscription message

---

packages/api/src/api/helix/eventSub/HelixEventSubSubscription.ts

Add eventSub cost to Helix

---

packages/api/src/api/helix/stream/HelixStreamApi.ts

Type: Bugfix
Fixes: #312
It's `stream/followed` but it should be `streams/followed`

Fix api endpoint

---

packages/api/src/api/helix/game/HelixGame.ts
packages/api/src/api/helix/video/HelixVideo.ts

Add image url helper methods for HelixGame and HelixVideo

---

packages/auth-electron/src/ElectronAuthProvider.ts
packages/auth/src/index.ts
packages/auth/src/providers/BaseAuthProvider.ts
packages/auth/src/providers/ClientCredentialsAuthProvider.ts
packages/auth/src/providers/RefreshingAuthProvider.ts

Fixes: #318 
This adds a new abstract base class called `BaseAuthProvider` that handles deduplication/queueing of requests, preventing multiple calls at once.
It then extends this class in all bundled `AuthProvider` implementations except `StaticAuthProvider` (which doesn't do any requests outside of the scope fetching).
I sent this PR to myself so that *other* people can review it. I tested a bunch of possible race conditions already, but I feel like there might still be some. Also, this feels too hacky anyway. Maybe someone has a good idea for refactoring this.
I know that the class doesn't have any doc comments yet. Please don't take this into account in your review - I'll be working on it when I can.

COMMUNITY REVIEW: implement queue for requests to bundled AuthProvider implementations

---

packages/chat/src/caps/twitchCommands/messageTypes/ClearChat.ts
packages/chat/src/caps/twitchCommands/messageTypes/UserNotice.ts
packages/chat/src/caps/twitchTags/messageTypes/ClearMsg.ts
packages/chat/src/commands/TwitchPrivateMessage.ts

Add missing sent date tag

---

jest.config.js
package.json
packages/api/src/api/helix/channel/HelixChannelApi.ts
packages/api/src/api/helix/stream/HelixStreamApi.ts
packages/auth/src/__tests__/helpers.test.ts
packages/auth/src/helpers.ts
packages/pubsub/src/SingleUserPubSubClient.ts
tsconfig.json
yarn.lock

Type: Bugfix
Fixes #342
Fixes #323
Closes #335
* Changes `compareScopes` from an `O(n*m)` operation to `O(n+m)`
* Accept kraken/helix scope equivalencies for `compareScopes`
* Accept `user:edit:broadcast` for `channel:manage:broadcast` in `compareScopes`
* `channel_subscriptions` => `channel:read:subscriptions` for `channel-subscribe-events-v1`
* `user:edit:broadcast` => `channel:manage:broadcast` for `updateChannelInfo`, `createStreamMarker`, and `replaceStreamTags`

fix(auth): accept equivalencies when comparing scopes

---

packages/api-call/src/errors/HttpStatusCodeError.ts
packages/auth-electron/src/ElectronAuthProvider.ts
packages/chat/src/ChatClient.ts
packages/common/src/emotes/BaseCheermoteList.ts
packages/easy-bot/src/BotCommand.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

packages/eventsub/src/events/EventSubChannelBanEvent.ts
packages/eventsub/src/events/EventSubChannelHypeTrainBeginEvent.ts
packages/eventsub/src/events/EventSubUserUpdateEvent.ts

Fixes: Mentioned on Discord
Matching similar events by calling it `startDate` instead of `bannedDate` so it's also ambiguous between ban and timeout.
As I've written it, `event.userEmailIsVerified` (`eventData.email_verified`) will be _`null`_ when `eventData.email` is an _empty string_, as per [Twitch documentation](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#user-update-event). `event.userEmail` uses `??` as if `eventData.email` could be _`undefined`_ (missing) but the Twitch documentation says it should be an _empty string_ even if you don't have the email scope. I'd expect to get _`null`_ from `event.userEmail` if `eventData.email` is an _empty string_ judging by Twurple documentation/typing. If you don't want to make that change (`??` -> `||` maybe or a …

Update for EventSub changes from 2022‑05‑17

---

packages/api/src/api/helix/moderation/HelixBanUser.ts
packages/api/src/api/helix/moderation/HelixModerationApi.ts
packages/api/src/index.ts

Type: Feature
Fixes: Part of #314
Continues work on the new moderation API endpoints. Adds the new ban/unban user functions.

Add ban/unban moderation API endpoints

---

packages/api/src/api/helix/moderation/HelixBanUser.ts
packages/api/src/api/helix/moderation/HelixBlockedTerm.ts
packages/api/src/api/helix/moderation/HelixModerationApi.ts
packages/api/src/index.ts

Type: Feature
Fixes: #314
This adds support for getting, adding, and removing blocked terms from a channel. This, combined with #326 and #361, should be the remainder of the new moderation API endpoints.

Add blocked terms to moderation API

---

packages/api/src/api/helix/stream/HelixStreamApi.ts

Type: Bugfix
Fixes: https://discord.com/channels/325552783787032576/350012219003764748/995436568007430164
`user_id` and `description` are meant to be body params (rather than query params): https://dev.twitch.tv/docs/api/reference#create-stream-marker
Supersedes #365 (rebased incorrectly & am lazy)

fix(api): pass create stream marker params to body

---

docs/getting-data/index.md
packages/api/src/api/helix/chat/HelixChatApi.ts
packages/api/src/index.ts

Type: Feature
Fixes: #369 
Adds support for the new Send Chat Announcement endpoint in the Helix API.

Send Chat Announcement via Helix

---

packages/api-call/package.json
packages/auth-electron/package.json
packages/auth-ext/package.json
packages/auth-tmi/package.json
packages/auth/package.json
packages/chat/package.json
packages/common/package.json
packages/ebs-helper/package.json
packages/eventsub/package.json
packages/pubsub/package.json

Type: Bugfix
Fixes: #383
**Description:**
Add `"types": "./lib/index.d.ts"` for each library with separate ES module paths. This allows TypeScript to detect the type declaration files when importing into ES module projects.
**Tests**

Fix: Missing TypeScript Definitions with ECMAScript Modules 

---

packages/api/package.json
packages/eventsub-ngrok/package.json

Type: Bugfix
Fixes: https://github.com/twurple/twurple/issues/383
Description:
Add "types": "./lib/index.d.ts" for each library with separate ES module paths. This allows TypeScript to detect the type declaration files when importing into ES module projects.
Added missing definitions from #384 for @twurple/api and @twurple/eventsub-ngrok

 Fix: Missing TypeScript Definitions with ECMAScript Modules (api, eventsub-ngrok)

---

.editorconfig

By default on github tab width is 8 spaces. 
That makes harder to read the source code.
So I suggest to set `indent_size = 4` for all files instead of only for `*.json` files.

set `indent_size = 4` for all files

---

packages/api/src/api/helix/video/HelixVideo.ts

Type:  #Bugfix
Fixes: #388 
`mutedSegmentData`
Array of muted segments in the video.
If there are no muted segments, the value will be `null`.
[twitch reference](https://dev.twitch.tv/docs/api/reference#get-videos)
my solution 
before   
```ts
muted_segments: HelixVideoMutedSegmentData[]; 
```
after  
```ts
muted_segments: HelixVideoMutedSegmentData[] | null; 
```

RE: Property 'mutedSegmentData' must allow null

---

packages/api/src/api/helix/prediction/HelixPrediction.ts

Type: Bugfix
Fixes: #398
It appears that winningOutcomeId wasn't included on the HelixPrediction object, even though it was being fetched.
Here I just copied over the equivalent code from `packages/eventsub/src/events/EventSubChannelPredictionEndEvent.ts`.
Since it's such a tiny thing I went ahead and wrote a quick commit even though I don't think anyone has seen it yet.

Expose winningOutcomeId and winningOutcome on the HelixPrediction object

---

packages/api/src/api/helix/clip/HelixClipApi.ts

Type: bugfix
As [reported on Discord](https://discord.com/channels/325552783787032576/350012219003764748/1032633418590208010), a small documentation tweak to indicate that clips are returned in descending order of views, rather than by creation date. Since it's a small change I didn't open an issue but if you would prefer I do so in the future I will.
See the Twitch documentation for [getting a broadcaster's clips](https://dev.twitch.tv/docs/api/clips#getting-a-broadcasters-clips) and [getting a game's clips](https://dev.twitch.tv/docs/api/clips#getting-a-games-clips).

Change clip fetch documentation to indicate clips are returned by view count, not creation date

---

packages/api/src/api/helix/chat/HelixEmote.ts
packages/api/src/index.ts
packages/api/src/interfaces/helix/chat.external.ts

Fixes: #426
Adds missing fields to HelixEmote base object, supported by all 3 emote calls: global, channel, and set emotes.

Add missing HelixEmote fields

---

packages/pubsub/src/messages/PubSubSubscriptionMessage.external.ts
packages/pubsub/src/messages/PubSubSubscriptionMessage.ts

Type: Feature
Fixes: #437 
Removed `giftDuration` getter and created `duration` getter instead that refers to all subscription contexts.
All issue comments have been taken into account.

feat(pubsub): add subscription duration

---

packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
packages/api/src/api/helix/moderation/HelixModerationApi.ts
packages/api/src/api/helix/moderation/HelixShieldModeStatus.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelShieldModeBeginEvent.ts
packages/eventsub-base/src/events/EventSubChannelShieldModeEndEvent.ts

Fixes: Discord
Removes beta tag from Shield Mode endpoints/events as this is now generally available from Twitch

remove beta tag from Shield Mode endpoints/events

---

packages/api/src/ApiClient.ts
packages/api/src/api/helix/HelixApiGroup.ts
packages/api/src/api/helix/channel/HelixChannel.ts
packages/api/src/api/helix/search/HelixChannelSearchResult.ts
packages/api/src/api/helix/stream/HelixStream.ts
packages/api/src/api/helix/stream/HelixStreamApi.ts
packages/api/src/api/helix/tag/HelixTag.ts
packages/api/src/api/helix/tag/HelixTagApi.ts
packages/api/src/interfaces/helix/channel.external.ts
packages/api/src/interfaces/helix/channel.input.ts
packages/api/src/interfaces/helix/search.external.ts
packages/api/src/interfaces/helix/stream.external.ts

Type: Feature
Fixes: Discord
Adds new custom tag fields and marks old tag fields/methods as deprecated

add custom tag support, deprecate old tag system

---

packages/api/src/ApiClient.ts
packages/api/src/api/helix/charity/HelixCharityApi.ts
packages/api/src/api/helix/charity/HelixCharityCampaign.ts
packages/api/src/api/helix/charity/HelixCharityCampaignAmount.ts
packages/api/src/api/helix/charity/HelixCharityCampaignDonation.ts
packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelCharityCampaignProgressEvent.ts
packages/eventsub-base/src/events/EventSubChannelCharityCampaignStartEvent.ts
packages/eventsub-base/src/events/EventSubChannelCharityCampaignStopEvent.ts
packages/eventsub-base/src/events/EventSubChannelCharityDonationEvent.ts
packages/eventsub-base/src/events/common/EventSubChannelCharityAmount.ts
packages/eventsub-base/src/subscriptions/EventSubChannelCharityCampaignProgressSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelCharityCampaignStartSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelCharityCampaignStopSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelCharityDonationSubscription.ts

Type: Feature
Fixes: Discord
Removes beta indicators for charity Helix endpoints/EventSub events as these have been marked as GA. Also fixes charity event CLI names.

Mark Charity as released, fix CLI names

---

packages/api/src/api/helix/chat/HelixChatApi.ts
packages/api/src/api/helix/chat/HelixChatChatter.ts
packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelShoutoutCreateEvent.ts
packages/eventsub-base/src/events/EventSubChannelShoutoutReceiveEvent.ts

Type: Feature
Fixes: Discord
Remove `@beta` tags from now GA shoutout events/endpoint, and one that was still on the `HelixChatChatter` object.

clear beta tag from GA items (shoutouts, chatters)

---

packages/eventsub-base/src/events/EventSubChannelShoutoutCreateEvent.ts

Fixes: Discord
Add missing moderator fields to EventSub shoutout create event object, minor doc wording cleanup.

Add moderator fields to shoutout create object

---

docs/getting-data/index.md
packages/pubsub/src/PubSubClient.ts
packages/pubsub/src/index.ts
packages/pubsub/src/messages/PubSubLowTrustUserChatMessage.external.ts
packages/pubsub/src/messages/PubSubLowTrustUserChatMessage.ts
packages/pubsub/src/messages/PubSubLowTrustUserTreatmentMessage.external.ts
packages/pubsub/src/messages/PubSubLowTrustUserTreatmentMessage.ts
packages/pubsub/src/messages/PubSubMessage.ts
packages/pubsub/src/messages/common/PubSubLowTrustUserContentBase.external.ts

Type: Feature
Fixes: #466 
Tested locally using `yalc`. 
`/monitor` and `/unmonitor` chat commands trigger `PubSubLowTrustUserTreatmentMessage` event, and the chat messages from the monitored user trigger `PubSubLowTrustUserChatMessage` event. Works like a charm. 
I want to point your attention to the following things:
1. `userId`, `userName`, and `userDisplayName` members of the `PubSubLowTrustUserTreatmentMessage` and  `PubSubLowTrustUserChatMessage` point to the moderator user, while the target suspicious user is behind `target*` and `sender*` members. Probably it makes sense to change it and make `user*` members point to the target user, and `moderator*` (or `updatedByUser*`) members point to the moderator?
2. Both `PubSubLowTrustUserTreatmentMessage` and …

pubsub: add support for low-trust users events

---

packages/ebs-helper/src/helpers.external.ts
packages/ebs-helper/src/helpers.ts

Type: Bugfix
Fixes: #470 
Fixed the order of parameters in methods setAnyConfigurationSegment & createConfigurationSegmentBody so calling methods parameters order matches.

Bugfix for #470 - update parameter order for EBS Helper methods

---

packages/api/src/interfaces/helix/moderation.input.ts

Type: Bugfix
Fixes: #
I noticed, since I wanted to get a list of moderators myself, that the "HelixModeratorFilter" always wants a UserID, even though this is optional from the Twitch Rest API. With this small bugfix it is now possible to get a bigger list than 20 moderators.

Make userId in helix moderator filter optional

---

packages/eventsub-ws/src/EventSubWsListener.ts

Fixes: #501 
Updated EventSub WS endpoint URL from `wss://eventsub-beta.wss.twitch.tv/ws` to `wss://eventsub.wss.twitch.tv/ws`
Twitch announcement: https://discuss.dev.twitch.tv/t/update-required-for-eventsub-websockets-beta-connection-url/45079

Update EventSub WS URL

---

packages/api/src/endpoints/stream/HelixStreamApi.ts

Type: Bugfix
When calling the `streams.getStreamKey` endpoint in the `api` package the following error is always displayed, no matter how the client is authed:
```
Error: Tried to make an API call with a scope but no context user ID
```
From my best understanding, this is because the `apiCall` options don't include the userId. Please correct me if I'm wrong here as I'm only just starting to dig into this package :)
**This PR adds the missing userId to the `apiCall` options and fixes the issue**

fix getStreamKey "no context user ID" error

---

packages/api/src/endpoints/channel/HelixAdSchedule.ts
packages/api/src/endpoints/channel/HelixChannelApi.ts
packages/api/src/endpoints/channel/HelixSnoozeNextAd.ts
packages/api/src/endpoints/channel/HelixSnoozeNextAdResult.ts
packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
packages/api/src/interfaces/endpoints/channel.external.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelAdBreakBeginEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelAdBreakBeginEvent.ts
packages/eventsub-base/src/subscriptions/EventSubChannelAdBreakBeginSubscription.ts

Type: Feature
Fixes: #532 
Twitch moved these to GA.
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelad_breakbegin
https://dev.twitch.tv/docs/api/reference/#get-ad-schedule
https://dev.twitch.tv/docs/api/reference/#snooze-next-ad
The timestamps are a bit different since they're using unix epoch timestamps, rather than the traditional strings as every other API endpoint. [Apparently that's expected?](https://github.com/twitchdev/issues/issues/879#issuecomment-1858380731)

Ad break endpoints

---

package.json
packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelChatClearEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelChatClearEvent.ts
packages/eventsub-base/src/events/EventSubChannelChatClearUserMessagesEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelChatClearUserMessagesEvent.ts
packages/eventsub-base/src/events/EventSubChannelChatMessageDeleteEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelChatMessageDeleteEvent.ts
packages/eventsub-base/src/index.ts
packages/eventsub-base/src/subscriptions/EventSubChannelChatClearSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelChatClearUserMessagesSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelChatMessageDeleteSubscription.ts

Type: Feature
Fixes: #535 (partial)
Adds the new EventSub events for [Chat Clear](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatclear), [Chat Clear User Messages](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatclear_user_messages), and [Chat Message Delete](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatmessage_delete)

add ChatClear, ChatClearUserMessages, ChatMessageDelete events

---

packages/api/src/endpoints/prediction/HelixPredictor.ts
packages/api/src/interfaces/endpoints/prediction.external.ts

Type: Bugfix
Fixes: #552
Updates the backing fields for `HelixPredictor` to the correct names per [Twitch docs](https://dev.twitch.tv/docs/api/reference/#get-predictions)

fix HelixPredictor user fields

---

packages/api/src/endpoints/moderation/HelixModeratedChannel.ts
packages/api/src/endpoints/moderation/HelixModerationApi.ts
packages/api/src/index.ts
packages/api/src/interfaces/endpoints/moderation.external.ts

Type: Feature 
Fixes: #551
Adds new [Get Moderated Channels](https://dev.twitch.tv/docs/api/reference/#get-moderated-channels) endpoint and paginated endpoint

add Get Moderated Channels

---

packages/api/src/endpoints/user/HelixUserApi.ts
packages/auth/src/__tests__/helpers.test.ts

Type: Bugfix
Fixes: #560 
The PR just replaces the requirement of `user:edit:broadcast` with `channel:manage:extensions` in the corresponding endpoints, the same way `channel:manage:broadcast` was used as a replacement for other endpoints in a past commit. Using a token with `user:edit:broadcast` still works as before since there's already a comparison equivalency defined in the auth package:
https://github.com/twurple/twurple/blob/9b94eee032a9089a276b23624ffc3d0326b5e06e/packages/auth/src/helpers.ts#L230-L241
Also added a minor test case you ensure no reverse `channel:manage:extensions` -> `user:edit:broadcast` ever happens
Basing this on the main branch since being a minor bugfix/improvement you probably won't backport this to 7.0

Update scope for user extensions endpoints

---

docs/getting-data/index.md
packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubAutoModMessageHoldEvent.external.ts
packages/eventsub-base/src/events/EventSubAutoModMessageHoldEvent.ts
packages/eventsub-base/src/events/EventSubAutoModMessageUpdateEvent.external.ts
packages/eventsub-base/src/events/EventSubAutoModMessageUpdateEvent.ts
packages/eventsub-base/src/events/EventSubAutoModSettingsUpdateEvent.external.ts
packages/eventsub-base/src/events/EventSubAutoModSettingsUpdateEvent.ts
packages/eventsub-base/src/events/EventSubAutoModTermsUpdateEvent.external.ts
packages/eventsub-base/src/events/EventSubAutoModTermsUpdateEvent.ts
packages/eventsub-base/src/events/EventSubChannelChatUserMessageHoldEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelChatUserMessageHoldEvent.ts
packages/eventsub-base/src/events/EventSubChannelChatUserMessageUpdateEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelChatUserMessageUpdateEvent.ts
packages/eventsub-base/src/events/common/EventSubAutoModLevel.ts
packages/eventsub-base/src/events/common/EventSubAutoModMessage.external.ts
packages/eventsub-base/src/events/common/EventSubAutoModResolutionStatus.ts
packages/eventsub-base/src/index.ts
packages/eventsub-base/src/subscriptions/EventSubAutoModMessageHoldSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubAutoModMessageUpdateSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubAutoModSettingsUpdateSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubAutoModTermsUpdateSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelChatUserMessageHoldSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelChatUserMessageUpdateSubscription.ts

Type: Feature
Fixes: #569 
Implemented subscription types:
- [automod.message.hold](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodmessagehold)
- [automod.message.update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodmessageupdate)
- [automod.settings.update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodsettingsupdate)
- [automod.terms.update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#automodtermsupdate)
- [channel.chat.user_message_hold](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatuser_message_hold)
- [channel.chat.user_message_update](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelchatuser_message_update)
Tested this manually using …

feat(eventsub): add automod events

---

packages/eventsub-base/src/index.ts

Type: Bugfix
Fixes: #594
Fixed the EventSubChannelAdBreakBeginEvent type not being exported

fix export of EventSubChannelAdBreakBeginEvent

---

docs/getting-data/index.md
packages/eventsub-base/src/events/EventSubChannelUnbanRequestCreateEvent.ts
packages/eventsub-base/src/events/EventSubChannelUnbanRequestResolveEvent.ts
packages/eventsub-base/src/subscriptions/EventSubChannelUnbanRequestCreateSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelUnbanRequestResolveSubscription.ts

Type: Bugfix
Fixes: -
- Fixed incorrect `authUserId` field in unban requests subscription types. The subscriptions now correctly use moderator's tokens (tested using `yalc`).
- Fixed ID pattern in unban requests subscription types. The subscription IDs now include the moderator's ID.
- Fix/improve docs

fix(eventsub): fix incorrect auth for unban requests subscription types

---

docs/getting-data/index.md
packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelSuspiciousUserMessageEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelSuspiciousUserMessageEvent.ts
packages/eventsub-base/src/events/EventSubChannelSuspiciousUserUpdateEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelSuspiciousUserUpdateEvent.ts
packages/eventsub-base/src/events/common/EventSubChannelSuspiciousUserLowTrustStatus.ts
packages/eventsub-base/src/index.ts
packages/eventsub-base/src/subscriptions/EventSubChannelSuspiciousUserMessageSubscription.ts
packages/eventsub-base/src/subscriptions/EventSubChannelSuspiciousUserUpdateSubscription.ts

Type: Feature
Fixes: #576 
Tested using `yalc`. The values ​​in the documentation differ in some places from the actual values ​​that Twitch sends. I tested all possible events and found the correct values for types.

Feat: EventSub Suspicious User Events

---

packages/eventsub-http/src/EventSubHttpBase.ts

Type: Bugfix/Improvement
Force `sha256` hmac to avoid algorithm downgrade and use `timingSafeEqual` to avoid timing attacks
Prevents notification forgery and secret key recovery (which would require node <17 or `--openssl-legacy-provider` for MD4 usage, and an extremely unrealistic number of http requests)

fix: harden eventsub signature verification

---

packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/events/EventSubChannelUpdateEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelUpdateEvent.ts
packages/eventsub-base/src/subscriptions/EventSubChannelUpdateSubscription.ts
packages/eventsub-http/src/EventSubHttpBase.ts

Type: Feature
Fixes: 
Switched `channel.update` subscription to version 2 and updated event data structure. Added `contentClassificationLabels` accessor and marked `isMature` flag as deprecated, mimicking its previous behavior.

Feat: Upgrade EventSub channel update event to v2

---

packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
packages/eventsub-base/src/EventSubBase.ts
packages/eventsub-base/src/EventSubListener.ts
packages/eventsub-base/src/events/EventSubChannelAutomaticRewardRedemptionAddV2Event.external.ts
packages/eventsub-base/src/events/EventSubChannelAutomaticRewardRedemptionAddV2Event.ts
packages/eventsub-base/src/events/common/EventSubChannelAutomaticReward.external.ts
packages/eventsub-base/src/events/common/EventSubChannelAutomaticReward.ts
packages/eventsub-base/src/index.ts
packages/eventsub-base/src/subscriptions/EventSubChannelAutomaticRewardRedemptionAddV2Subscription.ts

Type: Feature
Fixes: #619 
This implementation adds separate methods and classes for Automatic Reward Redemption V2, without replacing the existing V1 logic.
- ✅ Subscription confirmed working
- ❌ Events have not been tested

Feat: Add EventSub automatic reward redemption v2

---

packages/api/src/endpoints/chat/HelixChatApi.ts
packages/api/src/interfaces/endpoints/chat.external.ts
packages/api/src/interfaces/endpoints/chat.input.ts
packages/eventsub-base/src/events/EventSubChannelChatMessageEvent.external.ts
packages/eventsub-base/src/events/EventSubChannelChatMessageEvent.ts

Type: Feature
Fixes: #636 
This feature has not been tested during a shared chat session. The field `isSourceOnly` is present in the payload as `null`. Sending a message using an app access token with `forSourceOnly` set has no effect. At least, no errors were received from EventSub or API.

Feat: Sorce only chat message
