twurple/twurple

- src/API/Helix/HelixPagination.ts
- src/API/Helix/Stream/HelixStreamAPI.ts
- src/API/Helix/User/HelixFollow.ts
- src/API/Helix/User/HelixUser.ts
- src/API/Helix/User/HelixUserAPI.ts
Tested, as in builds for me ;)
> feat: add helix follows endpoint

- src/API/Channel/Channel.ts
Some properties in `ChannelData` weren't accessible trough `ChannelAPI`
> Add missing channel getters

- packages/twitch-chat-client/package.json
- packages/twitch-pubsub-client/package.json
- packages/twitch-webhooks/package.json
- packages/twitch/package.json
See https://docs.npmjs.com/files/package.json#repository
> Update repository meta fields to reflect monorepo setup

- packages/twitch-webhooks/docs/basic-usage/listening-to-events.md
Just fixing a doc with regard to twitch-webhooks
> fix: Docs update

- packages/twitch-chat-client/src/ChatClient.ts
> Fix typo in onRitual signature

- packages/twitch-chat-client/src/ChatClient.ts
> handle hyphen for host number of viewers

- packages/twitch-electron-auth-provider/src/index.ts
Now free of extraneous changes!
> Fixed bug in ElectronAuthProvider where getAccessToken could return undefined

- packages/twitch/src/API/Kraken/Channel/Channel.ts
- packages/twitch/src/API/Kraken/Channel/ChannelAPI.ts
> Add getChannelTeams to ChannelAPI and also scoped getTeams for Channel class

- packages/twitch-pubsub-client/src/Messages/PubSubRedemptionMessage.ts
> added default image field to redeem class

- .eslintrc.js
- packages/twitch-auth/src/TokenInfo.ts
- packages/twitch-chat-client/src/UserNotices/ChatCommunitySubInfo.ts
- packages/twitch/src/API/Helix/Bits/HelixBitsLeaderboardEntry.ts
- packages/twitch/src/API/Helix/Channel/HelixChannel.ts
- packages/twitch/src/API/Helix/ChannelPoints/HelixCustomReward.ts
- packages/twitch/src/API/Helix/ChannelPoints/HelixCustomRewardRedemption.ts
- packages/twitch/src/API/Helix/Extensions/HelixExtensionTransaction.ts
- packages/twitch/src/API/Helix/Moderation/HelixBan.ts
- packages/twitch/src/API/Helix/Moderation/HelixBanEvent.ts
- packages/twitch/src/API/Helix/Moderation/HelixModerator.ts
- packages/twitch/src/API/Helix/Moderation/HelixModeratorEvent.ts
- packages/twitch/src/API/Helix/Search/HelixChannelSearchResult.ts
- packages/twitch/src/API/Helix/Stream/HelixStream.ts
- packages/twitch/src/API/Helix/Stream/HelixStreamApi.ts
- packages/twitch/src/API/Helix/Subscriptions/HelixSubscription.ts
- packages/twitch/src/API/Helix/User/HelixFollow.ts
- packages/twitch/src/API/Helix/User/HelixUser.ts
- packages/twitch/src/API/Helix/Video/HelixVideo.ts
- packages/twitch/src/API/Kraken/User/User.ts
Fixes: _discussed in Discord_
- Adds the new login properties and "name" getters.
- Adds gifter data to `HelixSubscription`.
- Fixes some methods using the wrong properties.
- Consistent ordering of id/login/name property listing.
> Add many new user login props

- packages/twitch/src/API/Helix/Stream/HelixStream.ts
> add getThumbnailUrl function

- packages/twitch-chat-client/src/ChatClient.ts
> Fix typo & false warning condition check in ChatClient.whisper()

- packages/twitch/src/API/Helix/Stream/HelixStreamApi.ts
Type: Bugfix
Fixes: https://github.com/twurple/twurple/issues/289
Changes `broadcaster` to the requested `broadcaster_id`.
> Change broadcaster into requested broadcaster_id for replace stream tags

- packages/chat/src/ChatClient.ts
Fixes: https://github.com/twurple/twurple/issues/288
Adds user notices for the `onVipResult` listener and the `onMessageFailed` listener.
> Add user notices to the vip result and message failed listeners

- packages/eventsub/src/events/EventSubChannelPollEndEvent.ts
Fixes: Issue discussed on Discord.
> Add status to EventSubChannelPollEndEvent

- packages/chat/src/commands/TwitchPrivateMessage.ts
> Add isHighlight and isRedemption fields to Twitch private field

- packages/api/src/api/helix/clip/HelixClip.ts
> Add a duration property for the HelixClip class

- .eslintrc.js
- packages/api/src/api/helix/moderation/HelixAutoModSettings.ts
- packages/api/src/api/helix/moderation/HelixAutoModStatus.ts
- packages/api/src/api/helix/moderation/HelixBanEvent.ts
- packages/api/src/api/helix/moderation/HelixModerationApi.ts
- packages/api/src/api/helix/moderation/HelixModeratorEvent.ts
Type: Feature
Fixes: Part of #314
> Add new automod endpoints in the moderation API

- packages/chat/src/ChatClient.ts
- packages/chat/src/userNotices/ChatAnnouncementInfo.ts
Type: Feature
Fixes: #349 
New `ChatAnnouncementInfo` interface only features the announcement color for now
Please let me know if coding style has been respected
> Add new announcement USERNOTICE

- packages/chat/src/ChatClient.ts
Type: bugfix
Fixes: Incorrect link to docs (I let you know in Discord last week but you probably missed/forgot it due to other obv more important issues arising)
> fix docs sub gift spam example link

- docs/getting-data/index.md
- packages/api/src/api/helix/moderation/HelixModerationApi.ts
Type: Feature 
Fixes: #371 
Adds support for the new Delete Chat Messages endpoint in the Helix API
> Delete Chat Messages via Helix API

- docs/getting-data/index.md
- packages/api/src/api/helix/moderation/HelixModerationApi.ts
Type: Feature
Fixes: #373
Adds support for Add/Remove Channel Moderator endpoints via Helix API
> Add/Remove Channel Moderators via Helix

- docs/getting-data/index.md
- packages/api/src/api/helix/moderation/HelixModerationApi.ts
Type: Feature
Fixes: #375
Added support for new Add/Remove Channel VIP endpoints via Helix API
> Add/Remove VIPs via Helix

- docs/getting-data/index.md
- packages/api/src/ApiClient.ts
- packages/api/src/api/helix/whisper/HelixWhisperApi.ts
- packages/api/src/api/whispers/WhispersApi.ts
- packages/api/src/index.ts
Type: Feature
Fixes: #377
Added support for the new Send Whisper endpoint via Helix API, including new `WhispersApi` class.
> Send Whisper via Helix

- packages/api/src/api/helix/channel/HelixChannelApi.ts
Type: Bugfix
Fixes: N/A
Fixes the URL for `addVip` and `removeVip` in HelixChannelApi
> fix: URL for add/remove VIPs

- packages/api/src/api/helix/user/HelixUserApi.ts
Type: Bugfix
Fixes: #392 (the main breaking issue so the endpoint is at least usable)
> Fix api call method for Update User Extensions

- packages/eventsub-base/src/events/EventSubStreamOnlineEvent.ts
Type: Feature
Fixes: #418
Adds `streamId` getter to access the stream ID.
> feat(eventsub): expose stream ID in EventSubStreamOnlineEvent

- .eslintrc.js
- packages/api/src/ApiClient.ts
- packages/api/src/api/helix/charity/HelixCharityApi.ts
- packages/api/src/api/helix/charity/HelixCharityCampaign.ts
- packages/api/src/api/helix/charity/HelixCharityCampaignAmount.ts
- packages/api/src/api/helix/charity/HelixCharityCampaignDonation.ts
- packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
- packages/api/src/index.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelCharityCampaignProgressEvent.ts
- packages/eventsub-base/src/events/EventSubChannelCharityCampaignStartEvent.ts
- packages/eventsub-base/src/events/EventSubChannelCharityCampaignStopEvent.ts
- packages/eventsub-base/src/events/EventSubChannelCharityDonationEvent.ts
- packages/eventsub-base/src/events/common/EventSubChannelCharityAmount.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelCharityCampaignProgressSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelCharityCampaignStartSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelCharityCampaignStopSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelCharityDonationSubscription.ts
- packages/eventsub/src/index.ts
Type: Feature
Fixes: #422
Adds beta charity Helix endpoints and EventSub events
> Add Charity Helix endpoints/EventSub events

- packages/api/src/api/helix/chat/HelixChatApi.ts
- packages/api/src/api/helix/chat/HelixChatChatter.ts
- packages/api/src/index.ts
Type: Feature
Fixes: #424
Add Chatters beta Helix API endpoint
> Add Chatters beta Helix endpoint

- docs/getting-data/index.md
- packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
- packages/api/src/api/helix/moderation/HelixModerationApi.ts
- packages/api/src/api/helix/moderation/HelixShieldModeStatus.ts
- packages/api/src/index.ts
- packages/api/src/interfaces/helix/eventSub.external.ts
- packages/api/src/interfaces/helix/moderation.external.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelShieldModeBeginEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelShieldModeBeginEvent.ts
- packages/eventsub-base/src/events/EventSubChannelShieldModeEndEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelShieldModeEndEvent.ts
- packages/eventsub-base/src/events/EventSubChannelShieldModeEvent.external.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelShieldModeBeginSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelShieldModeEndSubscription.ts
Type: Feature
Fixes: #430
Adds support for new beta Shield Mode Helix endpoints and EventSub events
> add Shield Mode

- packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
- packages/api/src/interfaces/helix/eventSub.external.ts
Type: Bugfix
Fixes: Discussed in Discord
Fixes `broadcaster_user_id` condition for EventSub subscriptions
> fix EventSub broadcaster condition

- packages/api/src/api/helix/schedule/HelixScheduleApi.ts
Type: Bugfix
Fixes: Discussed in Discord
Fixes documentation title for `HelixScheduleApi`
> Fix HelixScheduleApi doc title

- packages/api/src/interfaces/helix/channel.external.ts
Type: Bugfix
Fixes: Discord
Fix custom tag update
> Tag update fix

- packages/api/src/api/helix/chat/HelixChatApi.ts
- packages/api/src/api/helix/eventSub/HelixEventSubApi.ts
- packages/api/src/interfaces/helix/chat.external.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelShoutoutCreateEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelShoutoutCreateEvent.ts
- packages/eventsub-base/src/events/EventSubChannelShoutoutReceiveEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelShoutoutReceiveEvent.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelShoutoutCreateSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelShoutoutReceiveSubscription.ts
Type: Feature
Fixes: Discord, #449
Adds new beta Shoutout Helix API endpoint and EventSub events
> Beta Shoutout Helix endpoint and EventSub events

- packages/api/src/api/helix/stream/HelixStreamApi.ts
Type: Bugfix
Fixes: Discord
Fixes field name in `getStreamByUserId`
> fix query param bug in getStreamByUserId

- packages/ebs-helper/src/helpers.external.ts
- packages/ebs-helper/src/helpers.ts
Type: Bugfix
Fixes: #472 
Update sendExtensionPubSubGlobalMessage to use new createPubSubGlobalMessageJwtData and createPubSubGlobalMessageBody methods.
> #472 Add Global Message Jwt/Body methods for PubSub

- packages/api/src/api/helix/chat/HelixChatBadgeVersion.ts
- packages/api/src/interfaces/helix/chat.external.ts
Fixes: #497 
Adds new Helix chat badge fields
> Add new Helix chat badge fields

- packages/ebs-helper/package.json
- packages/ebs-helper/src/classes/HelixExtensionSecretList.ts
- packages/ebs-helper/src/helpers.ts
- packages/ebs-helper/src/jwt.ts
> Replaced `jsonwebtoken` for `jose` in `ebs-helper`

- packages/eventsub-base/src/subscriptions/EventSubDropEntitlementGrantSubscription.ts
Type: Bugfix
Fixes: #515
Self-explanatory. CLI expects type `drop` for DropEntitlementGrant but the getCliTestCommand() provides `transaction`.
Reference: https://dev.twitch.tv/docs/cli/event-command/
> Fix DropEntitlementGrant subscription CLI name

- packages/api/src/endpoints/hypeTrain/HelixHypeTrainEvent.ts
> Fix hype train id incorrectly set to event id

- packages/api/src/endpoints/chat/HelixChatApi.ts
- packages/api/src/endpoints/chat/HelixSentChatMessage.ts
- packages/api/src/index.ts
- packages/api/src/interfaces/endpoints/chat.external.ts
- packages/api/src/interfaces/endpoints/chat.input.ts
Type: Feature
Fixes: #541
Adds new Helix send chat message endpoint
> add Helix send chat message

- packages/eventsub-base/src/events/common/EventSubChatMessage.external.ts
- packages/eventsub-base/src/index.ts
> Add missing EventSub chat exports and message fragments `text` field

- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
> fix EventSub subscriptions not using user context

- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
> fix EventSub chat topics not using context user

- packages/api/src/interfaces/endpoints/eventSub.external.ts
Fixes: #562 
Based on description at https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions
> Add missing HelixEventSubSubscriptionStatus values

- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelChatSettingsUpdateEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelChatSettingsUpdateEvent.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelChatSettingsUpdateSubscription.ts
> Add ChannelChatSettingsUpdate EventSub topic

- packages/api/src/endpoints/channel/HelixAdSchedule.ts
Type: Bugfix
Fixes: #573 
Also removes some commented imports within the file
> fix HelixAdSchedule returning wrong dates

- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
- packages/api/src/endpoints/moderation/HelixModerationApi.ts
- packages/api/src/endpoints/moderation/HelixUnbanRequest.ts
- packages/api/src/index.ts
- packages/api/src/interfaces/endpoints/moderation.external.ts
- packages/api/src/interfaces/endpoints/moderation.input.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelUnbanRequestCreateEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelUnbanRequestCreateEvent.ts
- packages/eventsub-base/src/events/EventSubChannelUnbanRequestResolveEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelUnbanRequestResolveEvent.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelUnbanRequestCreateSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelUnbanRequestResolveSubscription.ts
Type: Feature
Fixes: #574
Tested manually using `yalc`.
> Add unban requests support

- packages/api/src/endpoints/chat/HelixChatApi.ts
- packages/api/src/endpoints/chat/HelixEmote.ts
- packages/api/src/endpoints/chat/HelixEmoteBase.ts
- packages/api/src/endpoints/chat/HelixUserEmote.ts
- packages/api/src/index.ts
- packages/api/src/interfaces/endpoints/chat.external.ts
- packages/api/src/interfaces/endpoints/chat.input.ts
Type: Feature
Fixes: #581 
Tested locally using `yalc`.
> Feat: Add User Emotes Endpoint

- docs/getting-data/index.md
- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubUserWhisperMessageEvent.external.ts
- packages/eventsub-base/src/events/EventSubUserWhisperMessageEvent.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubUserWhisperMessageSubscription.ts
Type: Feature
Fixes: #584 
Tested using `yalc`.
> Feat: EventSub User Whisper Message Event

- docs/getting-data/index.md
- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
- packages/api/src/endpoints/moderation/HelixModerationApi.ts
- packages/api/src/endpoints/moderation/HelixWarning.ts
- packages/api/src/index.ts
- packages/api/src/interfaces/endpoints/moderation.external.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelWarningAcknowledgeEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelWarningAcknowledgeEvent.ts
- packages/eventsub-base/src/events/EventSubChannelWarningSendEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelWarningSendEvent.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelWarningAcknowledgeSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelWarningSendSubscription.ts
Type: Feature
Fixes: #592
I've tested this locally using `yalc`.
> Feat: Add Warnings API and EventSub Support

- docs/getting-data/index.md
- packages/api/src/endpoints/eventSub/HelixEventSubApi.ts
- packages/eventsub-base/src/EventSubBase.ts
- packages/eventsub-base/src/EventSubListener.ts
- packages/eventsub-base/src/events/EventSubChannelVipEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelVipEvent.ts
- packages/eventsub-base/src/index.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelVipAddSubscription.ts
- packages/eventsub-base/src/subscriptions/EventSubChannelVipRemoveSubscription.ts
Type: Feature
Fixes: #580 
Tested using `yalc`. I can confirm a successful subscription, but I can't test the events themselves because of a lack of VIP features on my channel.
> Feat: Add Eventsub Vip Events

- packages/eventsub-base/src/events/EventSubChannelHypeTrainBeginEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelHypeTrainBeginEvent.ts
- packages/eventsub-base/src/events/EventSubChannelHypeTrainEndEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelHypeTrainEndEvent.ts
- packages/eventsub-base/src/events/EventSubChannelHypeTrainProgressEvent.external.ts
- packages/eventsub-base/src/events/EventSubChannelHypeTrainProgressEvent.ts
Type: Feature
Fixes: #602 
Added `isGoldenKappaTrain` flag to EventSub Hype Train events.
> feat(eventsub): add `isGoldenKappaTrain` flag to hype train events

- packages/api/src/index.ts
Type: Bugfix
Fixes: N/A
This PR exports a type that was previously exported and is a type exposed to the user via `getCheermoteDisplayInfo` API:
https://twurple.js.org/reference/api/classes/HelixCheermoteList.html#getCheermoteDisplayInfo
> fix: export CheermoteDisplayInfo type
